### ISSUE TITLE
"Timed out waiting for display to respond"

### ISSUE THREAD

**Issue by Julien-ip** [GregDMeyer/IT8951#54]
Hello everyone,
I have a 7.8inch waveshare screen with an IT8951 driver. When I try to run the test.py script I have this message displayed :

`Initializing EPD...
Traceback (most recent call last):
  File "/home/julien/Documents/IT8951/test/integration/test.py", line 58, in <module>
    main()
  File "/home/julien/Documents/IT8951/test/integration/test.py", line 36, in main
    print('VCOM set to', display.epd.get_vcom())
  File "/usr/local/lib/python3.9/dist-packages/IT8951-0.1.1-py3.9-linux-armv7l.egg/IT8951/interface.py", line 115, in get_vcom
    self.spi.write_cmd(Commands.VCOM, 0)
  File "spi.pyx", line 230, in IT8951.spi.SPI.write_cmd
  File "spi.pyx", line 177, in IT8951.spi.SPI.write
  File "spi.pyx", line 117, in IT8951.spi.SPI.transfer
  File "spi.pyx", line 108, in IT8951.spi.SPI.wait_ready
TimeoutError: Timed out waiting for display to respond`

I can noticed small changes on the screen but nothing recognizable.
I tried before to use it on Windows and with the waveshare code for Raspbery pi but nothing happened so it's probably an hardware issue. 
But we never know if anyone has experienced a similar case.

**Comment by GregDMeyer** [comment]
Yeah, usually this is a hardware thing. (Especially since the other codes don't work either!) But, it doesn't necessarily mean your hardware is necessarily broken. I would check all your connections and make sure that everything is plugged in correctly and well!

Good luck!
