### ISSUE TITLE
TimeoutError: Ocassionally when updating screen

### ISSUE THREAD

**Issue by doebi** [GregDMeyer/IT8951#56]
Hi, I am running into this issue when updating the screen:

```
Traceback (most recent call last):
  File "/home/pi/show.py", line 41, in <module>
    update(sys.argv[1])
  File "/home/pi/show.py", line 11, in update
    display = AutoEPDDisplay(vcom=-1.46, spi_hz=1000000)
  File "/usr/local/lib/python3.9/dist-packages/IT8951/display.py", line 224, in __init__
    epd = EPD(vcom=vcom, bus=bus, device=device, data_hz=spi_hz)
  File "/usr/local/lib/python3.9/dist-packages/IT8951/interface.py", line 33, in __init__
    self.update_system_info()
  File "/usr/local/lib/python3.9/dist-packages/IT8951/interface.py", line 99, in update_system_info
    self.spi.write_cmd(Commands.GET_DEV_INFO)
  File "spi.pyx", line 230, in IT8951.spi.SPI.write_cmd
  File "spi.pyx", line 177, in IT8951.spi.SPI.write
  File "spi.pyx", line 117, in IT8951.spi.SPI.transfer
  File "spi.pyx", line 108, in IT8951.spi.SPI.wait_ready
TimeoutError: Timed out waiting for display to respond
```

My setup is a Raspi Zero W with the Waveshare HAT and the 7.8" (1842x1404) screen.

My goal is to have a task repeatedly updating the screen with an image retrieved from a server. After a couple of minutes/updates the sccreen gets stuck and I cannot update it anymore. Reboot of the raspi does not help, SPI kernel module reloading does not help. The only thing getting the screen unstuck is depowering, waiting for everything to empty and repower again. Unfortunately, having to unplug is a deal-breaker for me so I am looking for a solution to get the driver unstuck or prevent the issue beforehand.

What I tried already:
- eliminating the loading of images via wifi and loading them from disk 
- one python script with an infiinite loop running as systemd service
- decreasing the spi frequency, cause I read in some thread this could cause problems with the raspi zero

Unfortunately none of these helped solve my issue and I am still getting stuck after a coupld of updates. Any help appreaciated. Thanks.

**Comment by Max-Rider** [comment]
I am currently experiencing the same issue, did you ever resolve this?

**Comment by FutureSharks** [comment]
I also have the same issue!

I have a [CLI tool that displays weather data](https://github.com/FutureSharks/rpi-weather-display) on the screen periodically. After a while I see ghosting on the screen. Or half the screen turns grey. And sometimes I see the `Timed out waiting for display to respond` error also. If I restart my Python tool, a full screen refresh is done and it's fixed.

Any have any solutions?
